namespace Quay27.Application.Customers;

public record CustomerDto(
    Guid Id,
    int SortOrder,
    string InvoiceCode,
    DateTime BillCreatedAt,
    string NameAddress,
    string CreateMachine,
    string DraftStaff,
    int Quantity,
    string InstallStaffCm,
    bool ManagerApproved,
    bool Kio27Received,
    bool Export27,
    string Notes,
    string GoodsSenderNote,
    string AdditionalNotes,
    DateOnly SheetDate,
    string Status,
    bool IsDuplicate,
    DateTime CreatedDate,
    string CreatedBy,
    DateTime? UpdatedDate,
    string? UpdatedBy,
    IReadOnlyList<int> QueueIds);
