namespace Quay27.Application.Customers;

public record CustomerDto(
    Guid Id,
    int SortOrder,
    string InvoiceCode,
    DateTime BillCreatedAt,
    string NameAddress,
    string CreateMachine,
    string DraftStaff,
    string Quantity,
    string TotalAmount,
    string InspectorStaff,

    string InstallStaffCm,
    bool ManagerApproved,
    bool Kio27Received,
    bool Export27,
    bool FullSelfExport,
    string Notes,
    string GoodsSenderNote,
    string AdditionalNotes,
    DateOnly SheetDate,
    string Status,
    bool IsDuplicate,
    DateTime CreatedDate,
    string CreatedBy,
    DateTime? UpdatedDate,
    string? UpdatedBy,
    IReadOnlyList<int> QueueIds);
